build-job:
  stage: build
  script:
    - echo "Building server jar"
    - cd /home/voshooter/
    - gradle core:dist

deploy-prod:
  stage: deploy
  script:
    - echo "Running server jar"
    - cd /home/voshooter/core/build/libs/
    - nohup java -jar core-1.0.jar &
