build-job:
  stage: build
  script:
    - echo "Building server jar"
    - cd $CI_PROJECT_DIR
    - gradle core:dist
    - cp $CI_PROJECT_DIR/core/build/libs/core-1.0.jar ~/deploy/

deploy-prod:
  stage: deploy
  script:
    - echo "Running server jar"
    - cd
    - ./start-voshooter-server
