build-job:
  stage: build
  script:
    - echo "Building server jar"
    - cd $CI_PROJECT_DIR
    - gradle core:dist
  artifacts:
    paths:
      - $CI_PROJECT_DIR/core/build/libs/

deploy-prod:
  stage: deploy
  script:
    - echo "Running server jar"
    - cd $CI_PROJECT_DIR/core/build/libs/
    - nohup java -jar core-1.0.jar &
